platform :ios, '9.0'

target 'SwiftWeex' do
  use_frameworks!

  pod 'WeexSDK'
  pod 'WXDevtool'
  pod 'WeexPluginLoader'
  pod 'SDWebImage', '3.7.5'
  pod 'SocketRocket', '0.5.1'
  pod 'WechatOpenSDK', '~> 1.8.1'
  pod 'AMapNavi-NO-IDFA', '~> 5.4.0'
  pod 'AMapLocation-NO-IDFA', '~> 2.4.0'
  pod 'AMapSearch-NO-IDFA', '~> 5.4.0'

end
